-
  name: Deploy Database
  hosts: localhost
  vars_files: 
    - ./common-vars.yml
  roles:
    - db_servers

-
  name: Deploy web_server
  hosts: localhost
  vars_files: 
    - ./common-vars.yml
  roles:
    - web_servers

# - 
#   name: Install Python
#   hosts: localhost
#   roles:
#     - python