-
  name: Deploy Database
  hosts: localhost
  vars_files: 
    - ./common-vars.yml
  roles:
    - db_servers

-
  name: Deploy web_server
  hosts: localhost
  vars_files: 
    - ./common-vars.yml
  roles:
    - web_servers

- name: Install common app
  become: yes
  become_method: sudo
  gather_facts: True
  hosts: 
    - web_ips
    - db_ips
  roles:
    - install_dependences