- 
  name: Create VMs Engine
  hosts: localhost
  roles:
    - cp_engine

- 
  name: Install Python
  hosts: localhost
  roles:
    - python

-
  name: Deploy web_server
  hosts: localhost
  roles:
    - web_servers

-
  name: Deploy Database
  hosts: db_servers
  roles:
    - db_servers