  - name: create a web server
    gcp_compute_instance:
      name: web-server
      machine_type: e2-micro
      disks:
      - auto_delete: 'true'
        boot: 'true'
        initialize_params:
          source_image: "projects/ubuntu-os-cloud/global/images/family/ubuntu-1804-lts"
      network_interfaces:
      - access_configs:
        - name: Network Access
          type: ONE_TO_ONE_NAT
      zone: "{{ zone }}"
      project: "{{ project }}"
      auth_kind: "{{ auth_kind }}"
      service_account_file: "{{ service_account_file }}"
      state: present
    register: web-server

  - name: create a web server 2
    gcp_compute_instance:
      name: web-server2
      machine_type: e2-micro
      disks:
      - auto_delete: 'true'
        boot: 'true'
        initialize_params:
          source_image: "projects/ubuntu-os-cloud/global/images/family/ubuntu-1804-lts"
      network_interfaces:
      - access_configs:
        - name: Network Access
          type: ONE_TO_ONE_NAT
      zone: "{{ zone }}"
      project: "{{ project }}"
      auth_kind: "{{ auth_kind }}"
      service_account_file: "{{ service_account_file }}"
      state: present
    register: web-server2