  - name: update apt
    apt:
      update_cache: yes
      cache_valid_time: 3600
      upgrade: safe
      sudo: yes 
      
  - name: install python
    apt:
      name: python
      state: present
      sudo: yes
