  - name: wait for ssh
    wait_for_connection:
      delay: 5
      timeout: 300
      
  - name: update os
    apt:
      update_cache: true
      upgrade: safe

  - name: install python
    apt:
      name: python
      state: present
